export const skillsList = [
  { name: "Web Development", isSelected: false },
  { name: "Graphic Design", isSelected: false },
  { name: "Content Writing", isSelected: false },
  { name: "Digital Marketing", isSelected: false },
  { name: "Mobile App Development", isSelected: false },
  { name: "Data Entry", isSelected: false },
  { name: "Video Editing", isSelected: false },
  { name: "SEO Optimization", isSelected: false },
  { name: "Social Media Management", isSelected: false },
  { name: "UI/UX Design", isSelected: false },
  { name: "Illustration", isSelected: false },
  { name: "Photography", isSelected: false },
  { name: "Virtual Assistance", isSelected: false },
  { name: "Copywriting", isSelected: false },
  { name: "Transcription", isSelected: false },
  { name: "Animation", isSelected: false },
  { name: "Logo Design", isSelected: false },
  { name: "E-commerce Development", isSelected: false },
  { name: "Game Development", isSelected: false },
  { name: "Technical Support", isSelected: false },
  { name: "3D Modeling", isSelected: false },
  { name: "Voiceover", isSelected: false },
  { name: "Marketing Strategy", isSelected: false },
  { name: "WordPress Development", isSelected: false },
  { name: "Database Management", isSelected: false },
  { name: "Customer Support", isSelected: false },
  { name: "Blockchain Development", isSelected: false },
  { name: "Data Analysis", isSelected: false },
  { name: "Project Management", isSelected: false },
  { name: "Illustrator", isSelected: false },
  { name: "React.js", isSelected: false },
  { name: "Node.js", isSelected: false },
  { name: "Java", isSelected: false },
  { name: "Python", isSelected: false },
  { name: "Angular.js", isSelected: false },
  { name: "Vue.js", isSelected: false },
  { name: "Social Media Marketing", isSelected: false },
  { name: "Email Marketing", isSelected: false },
  { name: "C++", isSelected: false },
  { name: "Ruby on Rails", isSelected: false },
  { name: "Machine Learning", isSelected: false },
  { name: "AR/VR Development", isSelected: false },
  { name: "Script Writing", isSelected: false },
  { name: "Android Development", isSelected: false },
  { name: "iOS Development", isSelected: false },
  { name: "Salesforce", isSelected: false },
  { name: "Google AdWords", isSelected: false },
  { name: "Microsoft Excel", isSelected: false },
  { name: "Virtual Reality", isSelected: false },
  { name: "Augmented Reality", isSelected: false },
  { name: "TensorFlow", isSelected: false },
  { name: "Photoshop", isSelected: false },
  { name: "InDesign", isSelected: false },
  { name: "AutoCAD", isSelected: false },
  { name: "Excel VBA", isSelected: false },
  { name: "React Native", isSelected: false },
  { name: "Bootstrap", isSelected: false },
  { name: "Sass", isSelected: false },
  { name: "Node.js", isSelected: false },
  { name: "Express.js", isSelected: false },
  { name: "MongoDB", isSelected: false },
  { name: "MySQL", isSelected: false },
  { name: "PHP", isSelected: false },
  { name: "Laravel", isSelected: false },
  { name: "Swift", isSelected: false },
  { name: "Kotlin", isSelected: false },
  { name: "Redux", isSelected: false },
  { name: "GraphQL", isSelected: false },
  { name: "Vue.js", isSelected: false },
  { name: "Firebase", isSelected: false },
  { name: "Django", isSelected: false },
  { name: "Flask", isSelected: false },
  { name: "Shopify Development", isSelected: false },
  { name: "Magento Development", isSelected: false },
  { name: "Amazon Web Services (AWS)", isSelected: false },
  { name: "Microsoft Azure", isSelected: false },
  { name: "Content Management System (CMS)", isSelected: false },
  { name: "Responsive Web Design", isSelected: false },
  { name: "Search Engine Optimization (SEO)", isSelected: false },
  { name: "Google Analytics", isSelected: false },
  { name: "WordPress Customization", isSelected: false },
];
