export const ACTION_TYPE = {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  SIGN_UP: "SIGN_UP",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  LOCAL_STORAGE_EXTRACTOIN: "LOCAL_STORAGE",
  CHANGE_SIDE_NAV:"CHANGE_SIDE_NAV",
};
